version: '3'

services:
    rundeck:
        image: <rundeck-image>
        links:
          - mysql
        environment:
            RUNDECK_SERVER_UUID: <uuid>
            RUNDECK_PRIMARYSERVERID: <uuid>
            RUNDECK_GRAILS_URL: http://<your-host>
            RUNDECK_SERVER_FORWARDED: 'true'
            RUNDECK_DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
            RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME: org.rundeck.amazon-s3
            RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET: <aws-s3-bucket-name>
            RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION: <aws-region>
            AWS_ACCESS_KEY_ID: <aws-access-key-id>
            AWS_SECRET_KEY: <aws-secret-key>
            RUNDECK_API_TOKENS_DURATION_MAX: 0
            RUNDECK_PREAUTH_ENABLED: 'true'
            RUNDECK_PREAUTH_ATTRIBUTE_NAME: x-forwarded-remote-user-groups
            RUNDECK_PREAUTH_DELIMITER: ','
            RUNDECK_PREAUTH_USERNAME_HEADER: x-forwarded-user
            RUNDECK_PREAUTH_ROLES_HEADER: x-forwarded-roles
            RUNDECK_PREAUTH_REDIRECT_LOGOUT: 'true'
            RUNDECK_PREAUTH_REDIRECT_URL: /rundeck/logout
            
        expose: 
          - "4440" 
        ports:
          - 4440:4440
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
        expose: 
          - "3306"
        ports:
          - 3306:3306
    apache:
        image: <apache-oidc-image>
        links:
          - rundeck
        environment:
          - OIDC_PROVIDER_ISSUER=https://<auth0-domain>
          - OIDC_PROVIDER_AUTHORIZATION_ENDPOINT=https://<auth0-domain>/authorize
          - OIDC_PROVIDER_TOKEN_ENDPOINT=https://<auth0-domain>/oauth/token
          - OIDC_PROVIDER_TOKEN_ENDPOINT_AUTH=client_secret_post
          - OIDC_PROVIDER_USER_INFO_ENDPOINT=https://<auth0-domain>/userinfo
          - OIDC_PROVIDER_JWKS_URI=https://<auth0-domain>/.well-known/jwks.json
          - OIDC_CLIENT_ID=<auth0-client-id>
          - OIDC_CLIENT_SECRET=<auth0-client-secret>
          - OIDC_SCOPES="openid email profile"
          - OIDC_REDIRECT_URI=http://<you-host>/auth
          - OIDC_CRYPTO_PASSPHRASE=<passphrase>
          - OIDC_COOKIE_PATH=/
          - OIDC_PASS_CLAIMS_AS=environment
          - OIDC_PASS_USER_INFO_AS=claims
          - OIDC_LOGOUT_URL=https://<auth0-domain>/v2/logout?returnTo=http%3A%2F%2F<your-domain>%2Fauth%3Flogout%3Dhttp%253A%252F%252F<your-domain>&client_id=<auth0-client-id>
          - PROXY_PASS=http://rundeck:4440/
          - PROXY_PASS_REVERSE=http://rundeck:4440/ 
        ports:
          - 80:80
