version: '3'

services:
    rundeck:
        image: rundeck/rundeck:3.3.1
        links:
          - mysql
        environment:
            RUNDECK_GRAILS_URL: http://localhost
            RUNDECK_SERVER_FORWARDED: 'true'
            RUNDECK_DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
        expose:
          - "4440"
    nginx:
      image: nginx
      links:
        - rundeck
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 80:80
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
        ports:
          - 3306:3306