version: '3'

services:
    rundeck:
        image: <rundeck-builded-image>
        links:
          - mysql
        environment:
            RUNDECK_SERVER_UUID: 755d279b-1b78-44e5-88db-76d365b6c778
            RUNDECK_PRIMARYSERVERID: 755d279b-1b78-44e5-88db-76d365b6c778
            RUNDECK_GRAILS_URL: http://localhost
            RUNDECK_SERVER_FORWARDED: 'true'
            RUNDECK_DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
            RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME: org.rundeck.amazon-s3
            RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET: <aws-s3-bucket-name>
            RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION: <aws-region>
            AWS_ACCESS_KEY_ID: <aws-access-key-id>
            AWS_SECRET_KEY: <aws-secret-key>
            RUNDECK_API_TOKENS_DURATION_MAX: 0
            RUNDECK_PREAUTH_ENABLED: 'true'
            RUNDECK_PREAUTH_ATTRIBUTE_NAME: x-forwarded-remote-user-groups
            RUNDECK_PREAUTH_DELIMITER: ','
            RUNDECK_PREAUTH_USERNAME_HEADER: x-forwarded-user
            RUNDECK_PREAUTH_ROLES_HEADER: x-forwarded-roles
            RUNDECK_PREAUTH_REDIRECT_LOGOUT: 'true'
            RUNDECK_PREAUTH_REDIRECT_URL: /rundeck/logout
            
        expose: 
          - "4440" 
        ports:
          - 4440:4440
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
        expose: 
          - "3306"
        ports:
          - 3306:3306
    apache:
        image: <apache-builded-image>
        links:
          - rundeck
        volumes: 
          - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
          - 80:80
